// ─────────────────────────────────────────────────────────────────────────────
// SableAssent — Token Dispatch Panel
// File: src/components/TokenDispatchPanel.jsx
//
// Allows compliance admins to:
//   1. Auto-load "Pending" transactions that have a privy_wallet_address
//   2. Manually queue additional SAC1 recipients
//   3. Run pre-dispatch compliance checks per recipient
//   4. Export a Gnosis Safe Transaction Builder JSON batch file
//   5. Auto-create Transaction records with dispatch_status tracking
// ─────────────────────────────────────────────────────────────────────────────

'use client';

import { useState, useCallback, useEffect } from 'react';
import { Transaction } from '@/api/entities';

const SAC1_CONTRACT    = process.env.NEXT_PUBLIC_SAC1_POLYGON_CONTRACT  || '0xedd666802003d178c416b4e5dd6a82f76c2c7554';
const TREASURY_ADDRESS = process.env.NEXT_PUBLIC_SAFE_WALLET_ADDRESS || process.env.NEXT_PUBLIC_GNOSIS_SAFE_ADDRESS || '';
const CHAIN_ID         = '137'; // Polygon PoS

// ── Encode ERC-20 transfer calldata ──────────────────────────────────────────
function encodeTransfer(toAddress, amountSAC1) {
  const selector   = 'a9059cbb';
  const paddedAddr = toAddress.toLowerCase().replace('0x', '').padStart(64, '0');
  const amountWei  = BigInt(Math.round(amountSAC1 * 1e18));
  const paddedAmt  = amountWei.toString(16).padStart(64, '0');
  return `0x${selector}${paddedAddr}${paddedAmt}`;
}

// ── Build Gnosis Safe Transaction Builder JSON ────────────────────────────────
function buildSafeBatchJSON(recipients, chainId = CHAIN_ID) {
  const transactions = recipients
    .filter(r => r.status === 'approved')
    .map(r => ({
      to:    SAC1_CONTRACT,
      value: '0',
      data:  encodeTransfer(r.address, parseFloat(r.amount)),
      contractMethod: {
        inputs: [
          { name: '_to',    type: 'address', value: r.address },
          { name: '_value', type: 'uint256', value: String(Math.round(parseFloat(r.amount) * 1e18)) },
        ],
        name: 'transfer', payable: false,
      },
      contractInputsValues: {
        _to:    r.address,
        _value: String(Math.round(parseFloat(r.amount) * 1e18)),
      },
    }));

  return {
    version: '1.0', chainId,
    createdAt: Date.now(),
    meta: {
      name:             `SableAssent SAC1 Dispatch — ${new Date().toISOString().split('T')[0]}`,
      description:      `SAC1(Pos) token batch transfer from SableAssent treasury. ${transactions.length} recipients. Generated by SableAssent Token Dispatch Panel.`,
      txBuilderVersion: '1.16.5',
      createdFromSafeAddress: TREASURY_ADDRESS,
      createdFromOwnerAddress: '',
      checksum: '',
    },
    transactions,
  };
}

// ── Status badge ─────────────────────────────────────────────────────────────
function StatusBadge({ status }) {
  const map = {
    pending:   { bg: '#f1f5f9', color: '#64748b', label: '⏳ Pending' },
    checking:  { bg: '#ede9fe', color: '#7c3aed', label: '🔍 Checking…' },
    approved:  { bg: '#d1fae5', color: '#065f46', label: '✅ Approved' },
    flagged:   { bg: '#fef3c7', color: '#92400e', label: '⚠ Flagged' },
    blocked:   { bg: '#fee2e2', color: '#991b1b', label: '🚫 Blocked' },
    auto:      { bg: '#dbeafe', color: '#1d4ed8', label: '🤖 Auto-Queued' },
  };
  const s = map[status] || map.pending;
  return (
    <span style={{
      display: 'inline-block', padding: '3px 10px', borderRadius: 10,
      fontSize: 11, fontWeight: 600, background: s.bg, color: s.color, whiteSpace: 'nowrap',
    }}>{s.label}</span>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
export default function TokenDispatchPanel() {
  const [recipients, setRecipients]   = useState([]);
  const [form, setForm]               = useState({ address: '', amount: '', reference: '', beneficiary_name: '' });
  const [formError, setFormError]     = useState('');
  const [batchJSON, setBatchJSON]     = useState(null);
  const [exportStep, setExportStep]   = useState(null);
  const [checkingAll, setCheckingAll] = useState(false);
  const [dispatchLog, setDispatchLog] = useState([]);
  const [autoLoading, setAutoLoading] = useState(false);
  const [autoLoaded, setAutoLoaded]   = useState(0);
  const [dbTxIds, setDbTxIds]         = useState({}); // map reference → db record id

  // ── Auto-load pending transactions with wallet addresses ──────────────────
  useEffect(() => {
    loadPendingDispatch();
  }, []);

  const loadPendingDispatch = async () => {
    setAutoLoading(true);
    try {
      // Fetch all Pending transactions
      const pending = await Transaction.filter({ status: 'Pending' });

      // Filter those with a privy_wallet_address and not yet dispatched
      const queueable = pending.filter(tx =>
        tx.privy_wallet_address &&
        /^0x[a-fA-F0-9]{40}$/.test(tx.privy_wallet_address) &&
        tx.dispatch_status !== 'Dispatched' &&
        tx.dispatch_status !== 'Confirmed' &&
        tx.amount_sac1 > 0
      );

      if (queueable.length === 0) {
        setAutoLoading(false);
        return;
      }

      const newRecipients = queueable.map(tx => ({
        id:               `auto-${tx.id}`,
        dbId:             tx.id,
        address:          tx.privy_wallet_address,
        shortAddr:        `${tx.privy_wallet_address.slice(0, 10)}...${tx.privy_wallet_address.slice(-6)}`,
        amount:           String(tx.amount_sac1),
        reference:        tx.transaction_id || tx.id,
        beneficiary_name: tx.user_name || tx.user_email || 'SableAssent Customer',
        userEmail:        tx.user_email || '',
        status:           'auto',
        checks:           null,
        source:           tx.settlement_rail || 'Purchase',
        isAutoQueued:     true,
      }));

      // Avoid duplicates — don't re-add addresses already in queue
      setRecipients(prev => {
        const existingAddresses = new Set(prev.map(r => r.address.toLowerCase()));
        const fresh = newRecipients.filter(r => !existingAddresses.has(r.address.toLowerCase()));
        return [...prev, ...fresh];
      });

      // Track db IDs for later status update
      const idMap = {};
      queueable.forEach(tx => { idMap[tx.transaction_id || tx.id] = tx.id; });
      setDbTxIds(prev => ({ ...prev, ...idMap }));
      setAutoLoaded(queueable.length);
    } catch (err) {
      console.warn('[TokenDispatch] Auto-load failed:', err);
    }
    setAutoLoading(false);
  };

  // ── Add recipient manually ────────────────────────────────────────────────
  const handleAdd = (e) => {
    e.preventDefault();
    setFormError('');
    if (!/^0x[a-fA-F0-9]{40}$/.test(form.address)) {
      setFormError('Invalid Polygon wallet address (must be 0x + 40 hex chars)');
      return;
    }
    const amount = parseFloat(form.amount);
    if (!amount || amount <= 0)   { setFormError('Amount must be > 0'); return; }
    if (!form.reference.trim())   { setFormError('Reference / order ID is required'); return; }
    if (recipients.find(r => r.address.toLowerCase() === form.address.toLowerCase())) {
      setFormError('This address is already in the queue');
      return;
    }
    setRecipients(prev => [...prev, {
      id:               Date.now(),
      address:          form.address,
      shortAddr:        `${form.address.slice(0, 10)}...${form.address.slice(-6)}`,
      amount:           form.amount,
      reference:        form.reference,
      beneficiary_name: form.beneficiary_name || 'Unknown',
      status:           'pending',
      checks:           null,
      isAutoQueued:     false,
    }]);
    setForm({ address: '', amount: '', reference: '', beneficiary_name: '' });
  };

  // ── Remove recipient ──────────────────────────────────────────────────────
  const handleRemove = (id) => setRecipients(prev => prev.filter(r => r.id !== id));

  // ── Run compliance check on one recipient ─────────────────────────────────
  const runCheck = useCallback(async (id) => {
    setRecipients(prev => prev.map(r => r.id === id ? { ...r, status: 'checking' } : r));
    try {
      const r = recipients.find(r => r.id === id);
      // Simulate compliance check — in production wire to /api/dispatch/compliance-check
      await new Promise(res => setTimeout(res, 800));

      // Basic local checks
      const isValidAddress = /^0x[a-fA-F0-9]{40}$/.test(r.address);
      const amount         = parseFloat(r.amount);
      const requiresMultiSig = amount >= 500; // per SOP: 2-of-3 for >$500

      const checks = {
        address_valid:      isValidAddress,
        amount_valid:       amount > 0,
        sanctions_clear:    true, // wire to Chainalysis in production
        kyc_pass:           true, // wire to KYC provider in production
        requires_multisig:  requiresMultiSig,
        multisig_threshold: requiresMultiSig ? '2-of-3' : 'N/A',
        chainalysis_note:   'Screen destination wallet via Chainalysis before broadcast',
      };

      const newStatus = !isValidAddress ? 'blocked' : 'approved';
      setRecipients(prev => prev.map(rec =>
        rec.id === id ? { ...rec, status: newStatus, checks } : rec
      ));

      // Update dispatch_status in the database for auto-queued items
      if (r.dbId) {
        await Transaction.update(r.dbId, {
          dispatch_status:   newStatus === 'approved' ? 'Queued' : 'Awaiting Wallet',
          dispatch_queued_at: new Date().toISOString(),
        }).catch(() => {});
      }
    } catch (err) {
      setRecipients(prev => prev.map(r =>
        r.id === id ? { ...r, status: 'flagged', checks: { error: err.message } } : r
      ));
    }
  }, [recipients]);

  // ── Run checks on all pending/auto ───────────────────────────────────────
  const runAllChecks = async () => {
    setCheckingAll(true);
    for (const r of recipients.filter(r => r.status === 'pending' || r.status === 'auto')) {
      await runCheck(r.id);
    }
    setCheckingAll(false);
  };

  // ── Generate batch JSON ───────────────────────────────────────────────────
  const handleGenerate = () => {
    const approved = recipients.filter(r => r.status === 'approved');
    if (approved.length === 0) {
      alert('No approved recipients. Run compliance checks first.');
      return;
    }
    const json = buildSafeBatchJSON(recipients);
    setBatchJSON(json);
    setExportStep('preview');
  };

  // ── Download JSON file ────────────────────────────────────────────────────
  const handleDownload = () => {
    const blob = new Blob([JSON.stringify(batchJSON, null, 2)], { type: 'application/json' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `sableassent-dispatch-${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // ── Mark dispatched in DB, send emails, update analytics ─────────────────
  const handleLogToCompliance = async () => {
    const approved = recipients.filter(r => r.status === 'approved');
    const results  = [];
    const DISPATCH_FN = 'https://app.base44.com/api/apps/6a13d16e7f282082e39578f6/functions/sendDispatchNotification';

    for (const r of approved) {
      try {
        // Call the dispatch notification function (updates DB + sends email)
        const txHash    = r.txHash || r.batchTxHash || r.gnosis_tx_hash || '';
        const walletAddr = r.wallet || r.walletAddress || '';

        if (r.dbId && txHash) {
          // Use the backend function — handles DB update + email in one call
          const resp = await fetch(DISPATCH_FN, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              transactionId: r.transaction_id || r.reference,
              txHash,
              walletAddress: walletAddr,
              amountSac1:   parseFloat(r.amount || 0),
              amountUsd:    parseFloat(r.amountUsd || r.usd_amount || 0),
              userEmail:    r.email || r.user_email || '',
              userName:     r.name || r.user_name || '',
              blockNumber:  r.blockNumber || '',
              gasUsed:      r.gasUsed || '',
            }),
          });
          const data = await resp.json();
          results.push({ ref: r.reference, success: data.success, emailSent: data.emailSent, id: r.dbId });
        } else if (r.dbId) {
          // No tx hash yet — just update DB status
          await Transaction.update(r.dbId, {
            dispatch_status: 'Dispatched',
            status:          'Completed',
            notes:           (r.notes || '') + ` | Dispatched via Gnosis Safe batch on ${new Date().toISOString()}`,
          });
          results.push({ ref: r.reference, success: true, emailSent: false, note: 'No tx hash — email skipped', id: r.dbId });
        }
      } catch (err) {
        results.push({ ref: r.reference, success: false, error: err.message });
      }
    }

    // Trigger analytics refresh (fire and forget)
    fetch('https://app.base44.com/api/apps/6a13d16e7f282082e39578f6/functions/updateSalesAnalytics', {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ trigger: 'dispatch_batch' }),
    }).catch(() => {});

    setDispatchLog(results);
    setExportStep('done');
  };

  const approvedCount = recipients.filter(r => r.status === 'approved').length;
  const blockedCount  = recipients.filter(r => r.status === 'blocked').length;
  const autoCount     = recipients.filter(r => r.isAutoQueued).length;
  const totalSAC1     = recipients
    .filter(r => r.status === 'approved')
    .reduce((s, r) => s + parseFloat(r.amount || 0), 0);

  // ─────────────────────────────────────────────────────────────────────────
  return (
    <div className="td-panel">

      {/* ── Header ────────────────────────────────────────────────────────── */}
      <div className="td-header">
        <div>
          <h2 className="td-title">🚀 Token Dispatch Panel</h2>
          <p className="td-subtitle">
            Queue SAC1(PoS) transfers · Compliance screen · Export to Gnosis Safe
          </p>
        </div>
        <div className="td-header-meta">
          <div className="td-safe-badge">
            <span className="td-safe-dot" />
            <span>Treasury Safe: <code style={{ fontSize: 11 }}>
              {TREASURY_ADDRESS ? `${TREASURY_ADDRESS.slice(0, 10)}...${TREASURY_ADDRESS.slice(-6)}` : 'Not configured'}
            </code></span>
          </div>
          <a
            href={`https://app.safe.global/home?safe=matic:${TREASURY_ADDRESS}`}
            target="_blank" rel="noreferrer"
            className="td-safe-link"
          >Open in Safe ↗</a>
        </div>
      </div>

      {/* ── Auto-load banner ──────────────────────────────────────────────── */}
      {autoLoading && (
        <div style={{
          background: '#eff6ff', border: '1px solid #bfdbfe', borderRadius: 10,
          padding: '12px 16px', marginBottom: 16, fontSize: 13, color: '#1d4ed8',
          display: 'flex', alignItems: 'center', gap: 10,
        }}>
          ⏳ Scanning compliance database for pending SAC1 dispatch orders…
        </div>
      )}

      {!autoLoading && autoCount > 0 && (
        <div style={{
          background: '#dbeafe', border: '1px solid #93c5fd', borderRadius: 10,
          padding: '12px 16px', marginBottom: 16, fontSize: 13, color: '#1e40af',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }}>
          <span>🤖 <strong>{autoCount} pending order{autoCount > 1 ? 's' : ''}</strong> auto-loaded from compliance database — wallet addresses confirmed via Privy</span>
          <button
            onClick={loadPendingDispatch}
            style={{
              background: '#1d4ed8', color: '#fff', border: 'none', borderRadius: 6,
              padding: '4px 12px', fontSize: 12, cursor: 'pointer', fontWeight: 600,
            }}
          >↻ Refresh</button>
        </div>
      )}

      {!autoLoading && autoCount === 0 && (
        <div style={{
          background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: 10,
          padding: '12px 16px', marginBottom: 16, fontSize: 13, color: '#166534',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }}>
          <span>✅ No pending dispatch orders in database — all caught up</span>
          <button
            onClick={loadPendingDispatch}
            style={{
              background: '#16a34a', color: '#fff', border: 'none', borderRadius: 6,
              padding: '4px 12px', fontSize: 12, cursor: 'pointer', fontWeight: 600,
            }}
          >↻ Refresh</button>
        </div>
      )}

      {/* ── Stats row ─────────────────────────────────────────────────────── */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 20, flexWrap: 'wrap' }}>
        {[
          { label: 'In Queue',  value: recipients.length, color: '#64748b' },
          { label: 'Auto-Loaded', value: autoCount,       color: '#1d4ed8' },
          { label: 'Approved',  value: approvedCount,     color: '#065f46' },
          { label: 'Blocked',   value: blockedCount,      color: '#991b1b' },
          { label: 'Total SAC1', value: `${totalSAC1.toLocaleString()} SAC1`, color: '#92400e' },
        ].map(s => (
          <div key={s.label} style={{
            background: '#fff', border: '1px solid #e2e8f0', borderRadius: 10,
            padding: '10px 16px', minWidth: 100, textAlign: 'center',
          }}>
            <div style={{ fontSize: 20, fontWeight: 800, color: s.color }}>{s.value}</div>
            <div style={{ fontSize: 11, color: '#94a3b8', marginTop: 2 }}>{s.label}</div>
          </div>
        ))}
      </div>

      {/* ── Recipient queue ───────────────────────────────────────────────── */}
      {recipients.length > 0 && (
        <div style={{ marginBottom: 20 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
            <h3 style={{ fontSize: 14, fontWeight: 700, color: '#374151', margin: 0 }}>
              📋 Dispatch Queue ({recipients.length})
            </h3>
            <button
              onClick={runAllChecks}
              disabled={checkingAll || recipients.every(r => r.status === 'approved' || r.status === 'blocked')}
              style={{
                background: checkingAll ? '#e2e8f0' : '#1e3a5f',
                color: checkingAll ? '#94a3b8' : '#fff',
                border: 'none', borderRadius: 8, padding: '7px 16px',
                fontSize: 13, fontWeight: 700, cursor: checkingAll ? 'not-allowed' : 'pointer',
              }}
            >
              {checkingAll ? '🔍 Checking…' : '🔍 Screen All'}
            </button>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {recipients.map(r => (
              <div key={r.id} style={{
                background: '#fff', border: '1px solid #e2e8f0', borderRadius: 12,
                padding: '14px 16px',
                borderLeft: `4px solid ${r.status === 'approved' ? '#10b981' : r.status === 'blocked' ? '#ef4444' : r.isAutoQueued ? '#3b82f6' : '#e2e8f0'}`,
              }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginBottom: 4 }}>
                      <span style={{ fontFamily: 'monospace', fontSize: 12, color: '#374151', fontWeight: 600 }}>
                        {r.shortAddr}
                      </span>
                      <StatusBadge status={r.status} />
                      {r.isAutoQueued && (
                        <span style={{
                          fontSize: 10, background: '#dbeafe', color: '#1d4ed8',
                          padding: '2px 6px', borderRadius: 4, fontWeight: 600,
                        }}>AUTO</span>
                      )}
                    </div>
                    <div style={{ fontSize: 12, color: '#64748b', display: 'flex', gap: 16, flexWrap: 'wrap' }}>
                      <span>👤 {r.beneficiary_name}</span>
                      <span>💰 {parseFloat(r.amount).toLocaleString()} SAC1</span>
                      <span>🔖 {r.reference}</span>
                      {r.source && <span>📡 {r.source}</span>}
                      {r.userEmail && <span>✉️ {r.userEmail}</span>}
                    </div>
                    {r.checks && (
                      <div style={{ marginTop: 8, padding: '8px 10px', background: '#f8fafc', borderRadius: 8, fontSize: 11 }}>
                        {Object.entries(r.checks).map(([k, v]) => (
                          <span key={k} style={{
                            display: 'inline-block', marginRight: 12, marginBottom: 2,
                            color: v === true ? '#10b981' : v === false ? '#ef4444' : '#64748b',
                          }}>
                            {v === true ? '✅' : v === false ? '❌' : 'ℹ️'} {k.replace(/_/g, ' ')}: <strong>{String(v)}</strong>
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                  <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}>
                    {(r.status === 'pending' || r.status === 'auto' || r.status === 'flagged') && (
                      <button onClick={() => runCheck(r.id)}
                        style={{
                          background: '#ede9fe', color: '#7c3aed', border: 'none',
                          borderRadius: 6, padding: '5px 10px', fontSize: 11, fontWeight: 600, cursor: 'pointer',
                        }}>Screen</button>
                    )}
                    <button onClick={() => handleRemove(r.id)}
                      style={{
                        background: '#fee2e2', color: '#991b1b', border: 'none',
                        borderRadius: 6, padding: '5px 10px', fontSize: 11, fontWeight: 600, cursor: 'pointer',
                      }}>Remove</button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Manual add form ───────────────────────────────────────────────── */}
      <div style={{
        background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: 12,
        padding: '18px', marginBottom: 20,
      }}>
        <h3 style={{ fontSize: 14, fontWeight: 700, color: '#374151', marginBottom: 14, marginTop: 0 }}>
          ➕ Add Recipient Manually
        </h3>
        <form onSubmit={handleAdd}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 10 }}>
            <input
              value={form.address} onChange={e => setForm(f => ({ ...f, address: e.target.value }))}
              placeholder="0x… Polygon wallet address"
              style={{ padding: '9px 12px', borderRadius: 8, border: '1px solid #e2e8f0', fontSize: 13, gridColumn: '1/-1' }}
            />
            <input
              value={form.beneficiary_name} onChange={e => setForm(f => ({ ...f, beneficiary_name: e.target.value }))}
              placeholder="Customer name"
              style={{ padding: '9px 12px', borderRadius: 8, border: '1px solid #e2e8f0', fontSize: 13 }}
            />
            <input
              value={form.amount} onChange={e => setForm(f => ({ ...f, amount: e.target.value }))}
              placeholder="SAC1 amount" type="number" min="0.01" step="0.01"
              style={{ padding: '9px 12px', borderRadius: 8, border: '1px solid #e2e8f0', fontSize: 13 }}
            />
            <input
              value={form.reference} onChange={e => setForm(f => ({ ...f, reference: e.target.value }))}
              placeholder="Order / reference ID"
              style={{ padding: '9px 12px', borderRadius: 8, border: '1px solid #e2e8f0', fontSize: 13, gridColumn: '1/-1' }}
            />
          </div>
          {formError && (
            <div style={{ fontSize: 12, color: '#dc2626', marginBottom: 8 }}>⚠️ {formError}</div>
          )}
          <button type="submit" style={{
            background: '#1e3a5f', color: '#fff', border: 'none', borderRadius: 8,
            padding: '9px 20px', fontSize: 13, fontWeight: 700, cursor: 'pointer',
          }}>Add to Queue</button>
        </form>
      </div>

      {/* ── Action buttons ────────────────────────────────────────────────── */}
      {recipients.length > 0 && exportStep === null && (
        <button
          onClick={handleGenerate}
          disabled={approvedCount === 0}
          style={{
            width: '100%', padding: '14px', borderRadius: 12, border: 'none',
            background: approvedCount > 0 ? 'linear-gradient(135deg,#1e3a5f,#d4a017)' : '#e2e8f0',
            color: approvedCount > 0 ? '#fff' : '#94a3b8',
            fontWeight: 800, fontSize: 15, cursor: approvedCount > 0 ? 'pointer' : 'not-allowed',
          }}
        >
          ⬡ Generate Gnosis Safe Batch ({approvedCount} approved · {totalSAC1.toLocaleString()} SAC1)
        </button>
      )}

      {/* ── Preview + download ────────────────────────────────────────────── */}
      {exportStep === 'preview' && batchJSON && (
        <div style={{ background: '#fff', border: '1px solid #e2e8f0', borderRadius: 12, padding: 18 }}>
          <h3 style={{ fontSize: 14, fontWeight: 700, color: '#374151', marginBottom: 12, marginTop: 0 }}>
            📦 Batch Ready — {batchJSON.transactions.length} transaction{batchJSON.transactions.length !== 1 ? 's' : ''}
          </h3>
          <pre style={{
            background: '#f1f5f9', borderRadius: 8, padding: 12, fontSize: 11,
            overflow: 'auto', maxHeight: 200, marginBottom: 14,
          }}>
            {JSON.stringify(batchJSON, null, 2).slice(0, 600)}…
          </pre>
          <div style={{ display: 'flex', gap: 10 }}>
            <button onClick={handleDownload} style={{
              flex: 1, padding: '11px', borderRadius: 10, border: 'none',
              background: '#1e3a5f', color: '#fff', fontWeight: 700, fontSize: 13, cursor: 'pointer',
            }}>
              ⬇ Download JSON for Gnosis Safe
            </button>
            <button onClick={handleLogToCompliance} style={{
              flex: 1, padding: '11px', borderRadius: 10, border: 'none',
              background: '#d4a017', color: '#fff', fontWeight: 700, fontSize: 13, cursor: 'pointer',
            }}>
              ✅ Mark Dispatched in Compliance DB
            </button>
          </div>
          <div style={{ fontSize: 11, color: '#94a3b8', marginTop: 10, textAlign: 'center' }}>
            Upload JSON to <a href={`https://app.safe.global/home?safe=matic:${TREASURY_ADDRESS}`} target="_blank" rel="noreferrer" style={{ color: '#1e3a5f' }}>Gnosis Safe Transaction Builder ↗</a> · Requires 2-of-3 multi-sig for amounts ≥ $500
          </div>
        </div>
      )}

      {/* ── Done ─────────────────────────────────────────────────────────── */}
      {exportStep === 'done' && (
        <div style={{
          background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: 12,
          padding: 18, textAlign: 'center',
        }}>
          <div style={{ fontSize: 32, marginBottom: 8 }}>✅</div>
          <div style={{ fontWeight: 700, color: '#166534', marginBottom: 8 }}>Dispatch logged to compliance database</div>
          <div style={{ fontSize: 13, color: '#64748b', marginBottom: 14 }}>
            {dispatchLog.filter(d => d.success).length} of {dispatchLog.length} records updated to "Dispatched" status.
            Upload the JSON to Gnosis Safe to complete the blockchain transfer.
          </div>
          {dispatchLog.map(d => (
            <div key={d.ref} style={{ fontSize: 12, color: d.success ? '#166534' : '#dc2626', marginBottom: 4 }}>
              {d.success ? '✅' : '❌'} {d.ref} — {d.success ? 'Updated' : d.error}
            </div>
          ))}
          <button
            onClick={() => { setRecipients([]); setBatchJSON(null); setExportStep(null); setDispatchLog([]); loadPendingDispatch(); }}
            style={{
              marginTop: 12, background: '#1e3a5f', color: '#fff', border: 'none',
              borderRadius: 8, padding: '9px 20px', fontSize: 13, fontWeight: 700, cursor: 'pointer',
            }}
          >Start New Batch</button>
        </div>
      )}
    </div>
  );
}
